Repository prgrms-web-devcourse/Team-DarkNight-Kkini-FE, pull requests merged in 2023-04, with the labels that each got.

#183 신청서 목록 스켈레톤 로딩처리
  src/components/FoodParty/Application/ApplicationSkeleton.tsx
  src/hooks/query/useApplication.ts
  src/pages/food-party/application.tsx
Labels: Refactor

#189 Header 버그 대응
  public/favicon.ico
  public/images/kkini-logo.svg
  public/images/kkini-symbol.svg
  src/components/common/Layout/Header.tsx
  src/components/common/UserProfile.tsx
  src/hooks/query/useUser.ts
  src/pages/user/edit.tsx
Labels: Priority: High, Fix

#197 리드미에 발표 영상 링크 추가
  README.md
Labels: Priority: Low, Docs

#187 밥모임의 멤버 퇴장 및 강퇴 기능
  src/components/FoodParty/Application/ApplicationDrawer.tsx
  src/components/FoodParty/Create/index.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailCheckChangeStatusModal.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailModal.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyMemberItem.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyMemberList.tsx
  src/components/Search/SearchRestaurantContent.tsx
  src/components/Search/SearchRestaurantItem.tsx
  src/components/common/GoHomeWhenErrorInvoked.tsx
  src/hooks/query/useFoodParty.ts
  src/hooks/useSearchRestaurant.ts
  src/pages/404.tsx
  src/pages/food-party/application.tsx
  src/pages/food-party/create.tsx
  src/pages/food-party/detail/[partyId].tsx
  src/pages/food-party/detail/chat/[roomId].tsx
  src/pages/food-party/list/my.tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
  src/pages/index.tsx
  src/pages/oauth.tsx
  src/pages/user/[userId].tsx
  src/pages/user/edit.tsx
  src/services/foodParty.ts
  src/stores/foodParty.ts
  src/types/foodParty.ts
  src/utils/helpers/foodParty.ts
  src/utils/validations/foodParty.ts
Labels: Priority: High, Feature

#194 Google Analytics 페이지 추적을 위해 각 페이지마다 title 태그 추가
  src/components/FoodParty/Create/index.tsx
  src/components/FoodParty/FoodPartyList.tsx
  src/components/FoodParty/FoodPartyListItem.tsx
  src/pages/food-party/application.tsx
  src/pages/food-party/detail/[partyId].tsx
  src/pages/food-party/detail/chat/[roomId].tsx
  src/pages/food-party/list/my.tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
  src/pages/food-party/review/[partyId].tsx
  src/pages/index.tsx
  src/pages/oauth.tsx
  src/pages/user/[userId].tsx
  src/pages/user/edit.tsx
  src/utils/constants/routingPaths.ts
Labels: Priority: Low, Chore

#199 stores의 Restaurant.ts -> restaurant.ts로 네이밍 변경
  src/stores/restaurant.ts
Labels: Priority: Critical, Fix, Refactor

#196 검색 할 때, 사진 없으면 기본 사진 넣기
  public/images/default-restaurant.svg
  src/components/Search/SearchRestaurantContent.tsx
  src/components/Search/SearchRestaurantItem.tsx
  src/hooks/useSearchRestaurant.ts
  src/utils/constants/foodParty.ts
Labels: Priority: Medium, Refactor

#201 SSR 제거
  src/pages/404.tsx
  src/pages/food-party/create.tsx
  src/pages/food-party/detail/[partyId].tsx
  src/pages/food-party/detail/chat/[roomId].tsx
  src/pages/food-party/list/my.tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
  src/pages/food-party/review/[partyId].tsx
  src/pages/user/[userId].tsx
  src/utils/constants/routingPaths.ts
Labels: Priority: Medium, Refactor

#205 모바일 화면에서 네비게이션 바가 보이지 않는 현상 해결
  src/hooks/useAdjustHeightForMobileView.ts
  src/pages/_app.tsx
  src/styles/global.ts
  src/utils/helpers/debounce.ts
Labels: Priority: Medium, Design
