Repository prgrms-web-devcourse/Team-DarkNight-Kkini-FE, pull requests merged in 2023-03, with the labels that each got.

#39 가게 검색 모달 및 기능 구현
  next.config.js
  package-lock.json
  public/images/default_restaurant.svg
  src/components/DraggableDrawer/CreateCommunityDrawer.tsx
  src/components/DraggableDrawer/DrawerHeader.tsx
  src/components/DraggableDrawer/index.tsx
  src/components/SearchRestaurant/RestaurantItem.tsx
  src/components/SearchRestaurant/SearchRestaurantContent.tsx
  src/components/SearchRestaurant/index.tsx
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/hooks/useDrawer.ts
  src/hooks/useSearchRestaurant.ts
  src/stores/Restaurant.ts
  src/types/Restaurant.d.ts
Labels: Priority: High, Feature

#46 카카오맵 객체가 쌓이지 않고 현재 위치 이동, zoom in/out 되도록 변경
  next.config.js
  src/components/common/KakaoMap/index.tsx
  src/contexts/kakaoMap/index.tsx
  src/hooks/kakaoMap/useOperateKakaoMap.ts
  src/utils/helpers/kakaoMap.ts
Labels: Priority: High, Fix, Refactor

#47 Google maps photo Error
  next.config.js
Labels: Priority: Critical, Fix

#43 스타일변수 관리 변경(emotion -> chakra)
  src/components/common/Buttons/RecommendRandomRestaurantButton.tsx
  src/components/common/KakaoMap/CurrentLocationButton.tsx
  src/components/common/KakaoMap/ZoomInButton.tsx
  src/components/common/KakaoMap/ZoomOutButton.tsx
  src/components/common/Layout/index.tsx
  src/components/login/BottonDrawer.tsx
  src/pages/_app.tsx
  src/styles/chakra-theme.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: Design, Chore

#49 design: 로고 변경 & 배경 흰색으로 변경
  public/assets/kkini-logo.svg
  src/components/common/Layout/Header.tsx
  src/styles/global.ts
Labels: Design

#51 랜덤 맛집 뱃지를 Marker에서 Custom Overlay로 변경
  src/components/common/KakaoMap/index.tsx
  src/contexts/kakaoMap/randomRestaurant.tsx
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/hooks/useClickAway.ts
  src/styles/global.ts
  src/types/kakaoMap.ts
Labels: Priority: Medium, Feature, Refactor

#52 kakao, google 소셜로그인 연결
  .env.example
  env.d.ts
  src/components/login/GoogleButton.tsx
  src/components/login/KakaoButton.tsx
  src/components/login/LoginButton.tsx
  src/components/login/OAuth/GoogleButton.tsx
  src/components/login/OAuth/KakaoButton.tsx
  src/pages/oauth.tsx
  src/utils/apis/.gitkeep
  src/utils/apis/axios.ts
  src/utils/apis/interceptors.ts
Labels: Feature

#65 chore: 환경변수 분기 - 배포/개발
  .env.development
  .env.example
  .env.production
  env.d.ts
Labels: Chore, Build

#56 Recoil atom 네이밍 개선
  src/components/DraggableDrawer/index.tsx
  src/components/SearchRestaurant/SearchRestaurantContent.tsx
  src/components/common/Layout/Header.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/hooks/useDrawer.ts
  src/hooks/useSearchRestaurant.ts
  src/stores/Restaurant.ts
  src/stores/auth.ts
  src/stores/drawer.ts
Labels: Priority: Low, Refactor

#58 Types 폴더의 파일명 이름 개선
  src/stores/Restaurant.ts
  src/types/restaurant.ts
Labels: Priority: Low, Refactor

#63 구글 이미지 가져오는 로직 삭제
  src/components/KakaoMap/CurrentLocationButton.tsx
  src/components/KakaoMap/RandomRestaurantModal.tsx
  src/components/KakaoMap/ZoomInButton.tsx
  src/components/KakaoMap/ZoomOutButton.tsx
  src/components/KakaoMap/index.tsx
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/pages/index.tsx
  src/types/kakaoMap.ts
  src/utils/constants/errorMessage.ts
  src/utils/helpers/kakaoMap.ts
Labels: Priority: Medium, Feature, Refactor

#66 Oauth 페이지에서 isLogin -> isLoginState로 네이밍 변경
  src/pages/oauth.tsx
Labels: Priority: Critical, Fix

#68 @typescript-eslint/no-misused-promises eslint 에러 해결
  src/components/KakaoMap/index.tsx
Labels: Priority: Critical, Fix

#69 코딩컨벤션에 맞는 폴더명으로 수정
  src/components/Login/BottomDrawer.tsx
  src/components/Login/LoginButton.tsx
  src/components/Login/OAuth/GoogleButton.tsx
  src/components/Login/OAuth/KakaoButton.tsx
  src/components/common/Layout/Header.tsx
Labels: Priority: Critical, Fix, Refactor

#72 맛모임 생성 시 검색 결과 토글 적용
  .env.example
  env.d.ts
  src/components/SearchRestaurant/RestaurantItem.tsx
  src/components/SearchRestaurant/SearchRestaurantContent.tsx
  src/hooks/useSearchRestaurant.ts
  src/stores/Restaurant.ts
  src/types/kakaoSearch.ts
  src/types/restaurant.ts
  src/utils/helpers/kakaoMap.ts
  src/utils/helpers/kakaoSearch.ts
Labels: Priority: High, Feature

#76 내 밥모임 페이지 마크업
  src/components/FoodParty/.gitkeep
  src/components/KakaoMap/RandomRestaurantDrawer.tsx
  src/components/KakaoMap/RandomRestaurantModal.tsx
  src/components/KakaoMap/index.tsx
  src/components/Login/LoginButton.tsx
  src/components/common/BottomDrawer.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/contexts/kakaoMap/randomRestaurant.tsx
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/hooks/useClickAway.ts
  src/pages/food-party/[userId].tsx
  src/pages/food-party/detail/[partyId].tsx
  src/utils/helpers/elementHandler.ts
  src/utils/helpers/kakaoMap.ts
Labels: Priority: Medium, Fix, Feature, Refactor

#78 현재 위치를 나타내는 펄싱 서클 ui 구현
  src/components/KakaoMap/index.tsx
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/styles/global.ts
  src/utils/helpers/kakaoMap.ts
Labels: Priority: Low, Feature

#81 밥모임 생성하기 버튼 동작과 생성 페이지 대략적인 구조 마크업
  src/components/FoodParty/Create/index.tsx
  src/components/SearchRestaurant/RestaurantItem.tsx
  src/components/SearchRestaurant/SearchRestaurantContent.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/pages/food-party/create.tsx
  src/stores/Restaurant.ts
  src/styles/chakra-theme.ts
Labels: Priority: High, Feature

#79 로그인 안했을 경우, 밥모임 생성, 내 밥모임 클릭 시 로그인창 뜨도록 구현
  src/components/Login/LoginButton.tsx
  src/components/common/Layout/Header.tsx
  src/components/common/Layout/Navigation/CreateCommunityButton.tsx
  src/components/common/Layout/Navigation/NavigationButton.tsx
  src/components/common/Layout/Navigation/NavigationLinkButton.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/components/common/Layout/index.tsx
  src/types/modal.ts
  src/types/navigation.ts
Labels: Feature, Refactor

#84 소셜로그인 - 백엔드 엔드포인트로 연결
  .env.example
  env.d.ts
  src/components/Login/OAuth/GoogleButton.tsx
  src/components/Login/OAuth/KakaoButton.tsx
Labels: Priority: Critical, Fix, Chore

#86 밥모임 목록 페이지 스켈레톤 UI 구현
  src/components/FoodParty/FoodPartyList.tsx
  src/components/FoodParty/FoodPartyListItem.tsx
  src/components/FoodParty/FoodPartyListSkeleton.tsx
  src/components/common/AvatarGroupSkeleton.tsx
  src/pages/food-party/[userId].tsx
  src/types/foodParty.ts
Labels: Priority: Low, Feature

#90 react-query csr, ssr 세팅 설정
  package-lock.json
  package.json
  src/apis/axios.ts
  src/apis/interceptors.ts
  src/components/common/Layout/Header.tsx
  src/components/common/UserProfile.tsx
  src/hooks/query/useUser.ts
  src/pages/_app.tsx
  src/pages/oauth.tsx
  src/services/user.ts
Labels: Priority: High, Feature, Chore

#93 queryKey 상수화 위치 변경
  src/hooks/query/useUser.ts
  src/utils/constants/errorMessage.ts
  src/utils/constants/queryKeys.ts
Labels: Priority: High, Refactor

#95 밥모임 참여하기 버튼 구현
  src/components/KakaoMap/RandomRestaurantDrawer.tsx
  src/components/KakaoMap/index.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/contexts/kakaoMap/randomRestaurant.tsx
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/types/kakaoMap.ts
Labels: Priority: Low, Feature

#98 밥모임 생성 페이지 구현
  .eslintrc
  package-lock.json
  package.json
  public/images/drink.svg
  public/images/friend.svg
  public/images/meal.svg
  src/components/FoodParty/Create/FoodPartyCalendar.tsx
  src/components/FoodParty/Create/FoodPartyCapacity.tsx
  src/components/FoodParty/Create/FoodPartyCategory.tsx
  src/components/FoodParty/Create/FoodPartyTimePicker.tsx
  src/components/FoodParty/Create/index.tsx
  src/components/common/Accordion/AccordionBody.tsx
  src/components/common/Accordion/AccordionHeader.tsx
  src/components/common/Button/index.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/hooks/useSearchRestaurant.ts
  src/stores/Restaurant.ts
  src/types/foodParty.ts
  src/types/form.ts
  src/types/kakaoSearch.ts
  src/types/restaurant.ts
  src/utils/constants/foodparty.ts
Labels: Priority: Critical, Feature, Refactor

#105 신청서 Drawer 마크업 구현
  src/components/FoodParty/FoodPartyApplicationDrawer.tsx
Labels: Feature

#106 밥모임 생성 api 연결
  src/components/DraggableDrawer/index.tsx
  src/components/FoodParty/.gitkeep
  src/components/FoodParty/Create/index.tsx
  src/components/SearchRestaurant/RestaurantItem.tsx
  src/components/SearchRestaurant/SearchRestaurantContent.tsx
  src/components/common/Layout/index.tsx
  src/contexts/.gitkeep
  src/hooks/query/useFoodParty.ts
  src/hooks/useSearchRestaurant.ts
  src/services/foodParty.ts
  src/stores/Restaurant.ts
  src/types/foodParty.ts
  src/types/kakaoSearch.ts
  src/utils/constants/foodParty.ts
  src/utils/helpers/foodParty.ts
  src/utils/helpers/kakaoSearch.ts
Labels: Priority: High, Feature

#111 refresh token으로 자동로그인 처리
  package-lock.json
  package.json
  src/apis/axios.ts
  src/apis/interceptors.ts
  src/components/common/Layout/index.tsx
  src/services/auth.ts
  src/types/auth.ts
  src/utils/constants/errorCode.ts
Labels: Priority: High, Feature

#112 맛모임 가게 검색에서 밥모임 가게 검색으로 변경
  src/components/DraggableDrawer/DrawerHeader.tsx
Labels: Priority: Low, Refactor

#110 내 밥모임 목록 페이지, 내 밥모임 상세 페이지 구현
  package-lock.json
  src/apis/axios.ts
  src/components/FoodParty/Create/index.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailChangeStatusButton.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyMemberItem.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyMemberList.tsx
  src/components/FoodParty/FoodPartyList.tsx
  src/components/FoodParty/FoodPartyListItem.tsx
  src/components/FoodParty/FoodPartyListSkeleton.tsx
  src/components/KakaoMap/RandomRestaurantDrawer.tsx
  src/components/KakaoMap/RecommendRandomRestaurantButton.tsx
  src/components/KakaoMap/index.tsx
  src/components/Restaurant/RestaurantBottomDrawer.tsx
  src/components/SearchRestaurant/RestaurantItem.tsx
  src/components/common/AvatarGroupSkeleton.tsx
  src/components/common/Layout/Header.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/components/common/Layout/index.tsx
  src/contexts/kakaoMap/randomRestaurant.tsx
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/hooks/query/useFoodParty.ts
  src/hooks/useSearchRestaurant.ts
  src/pages/food-party/[userId].tsx
  src/pages/food-party/detail/[partyId].tsx
  src/pages/food-party/list/my.tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
  src/pages/oauth.tsx
  src/services/foodParty.ts
  src/types/foodParty.ts
  src/types/kakaoMap.ts
  src/types/kakaoSearch.ts
  src/types/restaurant.ts
  src/utils/constants/apiPaths.ts
  src/utils/constants/queryKeys.ts
  src/utils/constants/routingPaths.ts
  src/utils/helpers/foodParty.ts
  src/utils/helpers/kakaoSearch.ts
Labels: Priority: High, Feature, Design

#116 가게로 검색한 밥모임 목록 페이지 구현
  src/contexts/kakaoMap/randomRestaurant.tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
  src/services/foodParty.ts
  src/utils/constants/routingPaths.ts
Labels: Priority: High, Feature, Refactor

#113 리뷰 작성 페이지 마크업
  public/images/leader-high.svg
  public/images/leader-highest.svg
  public/images/leader-low.svg
  public/images/leader-lowest.svg
  public/images/leader-mid.svg
  public/images/member-high.svg
  public/images/member-highest.svg
  public/images/member-low.svg
  public/images/member-lowest.svg
  public/images/member-mid.svg
  src/components/FoodParty/Review/LeaderRadioGroup.tsx
  src/components/FoodParty/Review/MemberRadioGroup.tsx
  src/components/FoodParty/Review/ReviewBottomDrawer.tsx
  src/components/FoodParty/Review/ReviewItem.tsx
  src/pages/food-party/review/[partyId].tsx
  src/utils/constants/foodParty.ts
  src/utils/helpers/kakaoSearch.ts
Labels: Priority: High, Feature

#123 카카오맵 버튼에 애니메이션 적용
  src/components/KakaoMap/CurrentLocationButton.tsx
  src/components/KakaoMap/RecommendRandomRestaurantButton.tsx
  src/components/KakaoMap/ZoomInButton.tsx
  src/components/KakaoMap/ZoomOutButton.tsx
  src/components/common/Layout/index.tsx
  src/styles/animations.ts
  src/styles/chakraTheme.ts
Labels: Priority: Low, Design

#126 밥모임 상세 페이지에 스켈레톤 UI 구현하기
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailSkeleton.tsx
  src/pages/food-party/detail/[partyId].tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
Labels: Priority: Low, Feature

#129 토큰 재발급 과정 중 스켈레톤 UI 보여주기
  src/components/common/Layout/Header.tsx
  src/components/common/Layout/index.tsx
  src/stores/auth.ts
Labels: Priority: Medium, Refactor

#132 리뷰 API 통신 및 동작 구현
  src/components/FoodParty/Review/LeaderReviewList.tsx
  src/components/FoodParty/Review/MemberReviewList.tsx
  src/components/FoodParty/Review/ReviewBottomDrawer.tsx
  src/components/common/Button/index.tsx
  src/hooks/query/useFoodParty.ts
  src/pages/food-party/review/[partyId].tsx
  src/services/foodParty.ts
  src/types/foodParty.ts
  src/utils/constants/queryKeys.ts
Labels: Priority: High, Feature

#121 밥모임 신청 로직, 밥모임 상태 변경 로직 구현
  package-lock.json
  package.json
  src/components/FoodParty/FoodPartyApplicationDrawer.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailChangeStatusButton.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailContent.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailHeader.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailStatusButton.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailStatusCategory.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyMemberList.tsx
  src/components/FoodParty/FoodPartyList.tsx
  src/components/FoodParty/FoodPartyListItem.tsx
  src/components/common/Category.tsx
  src/components/common/GoHomeWhenErrorInvoked.tsx
  src/hooks/query/useFoodParty.ts
  src/pages/food-party/detail/[partyId].tsx
  src/pages/food-party/detail/chat/[roomId].tsx
  src/pages/food-party/list/my.tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
  src/services/foodParty.ts
  src/types/foodParty.ts
  src/utils/constants/routingPaths.ts
  src/utils/helpers/foodParty.ts
Labels: Priority: High, Feature, Refactor

#139 내 근처 밥모임 지도에 보여주기
  public/images/rice.png
  public/sausage.gif
  src/components/DraggableDrawer/index.tsx
  src/components/KakaoMap/index.tsx
  src/components/Login/LoginButton.tsx
  src/components/Restaurant/RestaurantBottomDrawer.tsx
  src/components/SearchRestaurant/RestaurantItem.tsx
  src/components/common/Layout/Header.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/components/common/Layout/index.tsx
  src/hooks/kakaoMap/useOperateKakaoMap.ts
  src/hooks/useDrawer.ts
  src/hooks/useNearFoodParty.ts
  src/services/foodParty.ts
  src/services/restaurant.ts
  src/stores/drawer.ts
  src/types/foodParty.ts
  src/types/modal.ts
  src/utils/constants/kakaoMap.ts
  src/utils/helpers/foodParty.ts
  src/utils/helpers/kakaoMap.ts
Labels: Priority: High, Feature

#142 이전 merge 충돌로 해결한 커밋
  package-lock.json
  src/utils/helpers/foodParty.ts
Labels: Priority: Critical, Fix

#137 내 정보 페이지 마크업
  src/components/DraggableDrawer/index.tsx
  src/components/FoodParty/Review/ReviewBottomDrawer.tsx
  src/components/User/MyPageButton.tsx
  src/components/User/MyPageCount.tsx
  src/components/User/MyPageItem.tsx
  src/components/common/Button/index.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/components/common/UserProfile.tsx
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/hooks/query/useUser.ts
  src/hooks/useDrawer.ts
  src/pages/food-party/review/[partyId].tsx
  src/pages/user/[userId].tsx
  src/services/auth.ts
  src/services/user.ts
  src/utils/constants/queryKeys.ts
  tsconfig.json
Labels: Priority: High, Feature

#148 Google maps api 관련 코드 삭제
  .env.example
  env.d.ts
  next.config.js
  package-lock.json
  package.json
  src/pages/_document.tsx
  tsconfig.json
Labels: Priority: Low

#149 fix: navigtion 상태값 변경된 네이밍으로 수정
  src/components/common/Layout/Navigation/index.tsx
Labels: Priority: Critical, Fix

#146 밥모임 채팅
  src/components/FoodParty/FoodPartyDetail/Chat/MessageInput.tsx
  src/components/FoodParty/FoodPartyDetail/Chat/MessageList.tsx
  src/components/FoodParty/FoodPartyDetail/Chat/MessageListitem.tsx
  src/components/KakaoMap/CurrentLocationButton.tsx
  src/components/KakaoMap/ZoomInButton.tsx
  src/components/KakaoMap/ZoomOutButton.tsx
  src/hooks/query/useFoodParty.ts
  src/hooks/query/useUser.ts
  src/pages/food-party/detail/[partyId].tsx
  src/pages/food-party/detail/chat/[roomId].tsx
  src/pages/food-party/list/my.tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
  src/pages/food-party/review/[partyId].tsx
  src/pages/user/[userId].tsx
  src/services/foodParty.ts
  src/types/foodParty.ts
  src/utils/constants/queryKeys.ts
  src/utils/helpers/chat.ts
  src/utils/helpers/foodParty.ts
Labels: Priority: High, Feature

#150 404 페이지 작성
  public/images/sausage.gif
  src/components/FoodParty/FoodPartyListItem.tsx
  src/components/common/GoHomeWhenErrorInvoked.tsx
  src/pages/404.tsx
Labels: Priority: Medium, Feature

#153 내 정보 수정 페이지
  public/fonts/GangwonEdu_OTFBoldA.woff
  src/components/DraggableDrawer/DrawerHeader.tsx
  src/components/SearchRestaurant/SearchRestaurantContent.tsx
  src/components/User/Edit/UserIconForm.tsx
  src/components/User/UserProfileButton.tsx
  src/components/User/UserProfileCount.tsx
  src/components/User/UserProfileItem.tsx
  src/components/common/Button/index.tsx
  src/components/common/Layout/index.tsx
  src/components/common/UserProfile.tsx
  src/hooks/query/useUser.ts
  src/hooks/useSearchRestaurant.ts
  src/pages/food-party/review/[partyId].tsx
  src/pages/user/[userId].tsx
  src/pages/user/edit.tsx
  src/services/user.ts
  src/styles/fonts.ts
  src/utils/constants/routingPaths.ts
  src/utils/validations/.gitkeep
  src/utils/validations/user.ts
Labels: Priority: High, Feature

#151 신청서 UI, 기능구현
  package-lock.json
  public/images/fork-knife.svg
  src/components/FoodParty/Application/ApplicationDrawer.tsx
  src/components/FoodParty/Application/ApplicationItem.tsx
  src/components/FoodParty/Application/ReceivedApplication.tsx
  src/components/FoodParty/Application/SentApplication.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailHeader.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailStatusCategory.tsx
  src/components/FoodParty/FoodPartyListItem.tsx
  src/components/Restaurant/RestaurantBottomDrawer.tsx
  src/components/SearchRestaurant/RestaurantItem.tsx
  src/components/common/Category.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/components/common/StatusBadge.tsx
  src/components/common/UserProfile.tsx
  src/hooks/query/useApplication.ts
  src/pages/food-party/application.tsx
  src/pages/user/[userId].tsx
  src/services/application.ts
  src/services/user.ts
  src/styles/global.ts
  src/types/application.ts
  src/types/auth.ts
  src/utils/constants/queryKeys.ts
  src/utils/constants/routingPaths.ts
  src/utils/helpers/application.ts
Labels: Priority: High, Feature

#160 근처의 기준, 화면에 보이는 지도 반경으로 변경 & 에러 수정
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/utils/helpers/kakaoMap.ts
Labels: Priority: High, Fix, Refactor

#162 밥모임 인원 초과 & 신청서 승인할 경우, 인원초과됐다는 메시지 보여주기
  src/hooks/query/useApplication.ts
  src/services/application.ts
  src/services/auth.ts
  src/types/error.ts
  src/utils/constants/errorCode.ts
Labels: Priority: High, Refactor

#155 채팅방 개선
  src/components/FoodParty/FoodPartyDetail/Chat/FoodPartyDetailChatLoadingSpinner.tsx
  src/components/FoodParty/FoodPartyDetail/Chat/MessageInput.tsx
  src/components/FoodParty/FoodPartyDetail/Chat/MessageList.tsx
  src/components/FoodParty/FoodPartyDetail/Chat/MessageListitem.tsx
  src/components/common/Layout/Navigation/NavigationButton.tsx
  src/pages/food-party/detail/chat/[roomId].tsx
  src/types/foodParty.ts
  src/utils/helpers/chat.ts
Labels: Priority: Medium, Feature

#166 svg 대신 react-icons로 사용
  public/images/fork-knife.svg
  src/components/FoodParty/Application/ApplicationItem.tsx
  src/components/common/Layout/Navigation/index.tsx
Labels: Design

#167 review ui 수정(말줄임표, 리뷰UI)
  src/pages/food-party/review/[partyId].tsx
Labels: Priority: High, Design

#165 foodPartySearchDrawer 애니메이션 및 동작 수정
  src/components/DraggableDrawer/CreateCommunityDrawer.tsx
  src/components/DraggableDrawer/index.tsx
  src/components/KakaoMap/index.tsx
  src/components/Search/SearchRestaurantContent.tsx
  src/components/Search/SearchRestaurantDrawer.tsx
  src/components/Search/SearchRestaurantDrawerHeader.tsx
  src/components/Search/SearchRestaurantItem.tsx
  src/components/Search/index.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/components/common/Layout/index.tsx
  src/hooks/kakaoMap/useOperateKakaoMap.ts
  src/hooks/useDragDrawer.ts
  src/hooks/useSearchRestaurant.ts
  src/stores/drawer.ts
Labels: Priority: High, Refactor

#168 랜덤 맛집 커스텀 오버레이 디자인
  public/images/default_restaurant.svg
  public/images/golden-fork.svg
  public/images/restaurant-badge.svg
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/styles/global.ts
Labels: Priority: Medium, Design

#164 채팅방 새로고침 시 실패하는 현상 해결
  src/pages/food-party/detail/chat/[roomId].tsx
Labels: Priority: High, Fix

#156 밥모임 상세 페이지에서 상태 변경 시 모달 출력
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailCheckChangeStatusModal.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyDetailStatusButton.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyMemberItem.tsx
  src/components/FoodParty/FoodPartyDetail/FoodPartyMemberList.tsx
  src/components/FoodParty/FoodPartyListItem.tsx
  src/components/common/AvatarGroupSkeleton.tsx
  src/components/common/Layout/Header.tsx
  src/pages/food-party/detail/[partyId].tsx
  src/utils/helpers/foodParty.ts
Labels: Priority: Medium, Fix, Feature, Refactor

#169 밥모임 생성 페이지 디자인 수정
  public/images/manner.svg
  src/components/FoodParty/Create/FoodPartyCalendar.tsx
  src/components/FoodParty/Create/index.tsx
  src/utils/constants/foodParty.ts
Labels: Priority: High, Refactor

#170 유저 프로필 스코어 스타일 수정
  src/pages/user/[userId].tsx
Labels: Priority: High, Refactor

#171 로그인 시 뜨는 로딩을 소시지로 변경
  src/components/common/UserProfile.tsx
  src/pages/oauth.tsx
Labels: Priority: Medium, Feature

#173 가게로 검색한 밥모임 목록 페이지에서는 리뷰하기 버튼이 안 뜨도록 구현
  src/components/FoodParty/FoodPartyList.tsx
  src/components/FoodParty/FoodPartyListItem.tsx
  src/pages/food-party/list/my.tsx
  src/pages/food-party/list/restaurant/[placeId].tsx
Labels: Priority: Critical, Feature

#174 밥모임 생성 drawer translateY 수정
  src/components/Search/SearchRestaurantDrawer.tsx
Labels: Priority: High, Fix

#178 랜덤 맛집 커스텀 오버레이 누르면 지도가 이동하는 기능 삭제
  src/components/KakaoMap/index.tsx
Labels: Priority: Low, Refactor

#176 README 파일 작성
  README.md
Labels: Priority: Medium, Docs

#181 README 파일 개요 부분 수정
  README.md
Labels: Priority: Low, Docs

#182 fix: 연속 리뷰 안되는 버그 해결
  src/components/FoodParty/Review/ReviewBottomDrawer.tsx
Labels: Priority: High, Fix
