Repository prgrms-web-devcourse/Team-DarkNight-Kkini-FE, pull requests merged in 2023-05, with the labels that each got.

#208 지도에 올라온 이미지 드래그 막기
  package-lock.json
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/hooks/useNearFoodParty.ts
Labels: Priority: High, Fix

#216 hotfix: 신청서 api 변경되어 에러 대응
  src/components/FoodParty/Application/ReceivedApplication.tsx
  src/components/FoodParty/Application/SentApplication.tsx
  src/services/application.ts
Labels: Priority: Critical, Fix

#212 브라우저 환경에서 동작하는 debounce 함수에서 사용되는 timerId 타입을 number로 변경
  src/utils/helpers/debounce.ts
Labels: Priority: Low, Refactor
