Repository prgrms-web-devcourse/Team-DarkNight-Kkini-FE, pull requests merged in 2023-02, with the labels that each got.

#2 React Query Client 및 Provider 설정
  src/pages/_app.tsx
  tsconfig.json
Labels: Priority: Medium, Chore

#7 필요한 디펜던시 설치 & 설정
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/components/common/Layout/Header.tsx
  src/components/common/Layout/Navigation.tsx
  src/components/common/Layout/index.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/stores/.empty
  tsconfig.json
Labels: Priority: Critical, Chore

#17 globalStyle, theme 설정(emotion사용)
  src/components/common/Layout/index.tsx
  src/pages/_app.tsx
  src/styles/emotion.d.ts
  src/styles/global.ts
  src/styles/theme.ts
  tsconfig.json
Labels: Design, Chore

#12 카카오맵 렌더링
  .eslintrc
  package-lock.json
  package.json
  src/components/common/.empty
  src/components/common/KakaoMap/CurrentLocationButton.tsx
  src/components/common/KakaoMap/ZoomInButton.tsx
  src/components/common/KakaoMap/ZoomOutButton.tsx
  src/components/common/KakaoMap/index.tsx
  src/components/common/Layout/Header.tsx
  src/components/common/Layout/Navigation.tsx
  src/pages/index.tsx
  src/utils/constants/errorMessage.ts
  tsconfig.json
Labels: Priority: High, Feature, Design, Chore

#14 feat: Navigation bar UI 컴포넌트 구현
  src/components/common/Layout/Navigation.tsx
  src/components/common/Layout/Navigation/NavigationButton.tsx
  src/components/common/Layout/Navigation/index.tsx
Labels: Feature, Design

#19 feat: 버튼 공통 컴포넌트 구현
  src/components/common/Button/index.tsx
Labels: Feature

#21 Header UI, 폰트적용
  public/assets/kkini-logo.svg
  public/fonts/GangwonEdu_OTFBoldA.woff
  public/fonts/Pretendard-Regular.woff
  src/assets/.empty
  src/components/common/Layout/Header.tsx
  src/components/common/Layout/index.tsx
  src/styles/fonts.ts
Labels: Feature, Design

#26 밥모임 생성을 위한 Draggable Drawer 구현
  src/components/DraggableDrawer/CreateCommunityDrawer.tsx
  src/components/DraggableDrawer/DrawerHeader.tsx
  src/components/DraggableDrawer/index.tsx
  src/components/common/Layout/Navigation/CreateCommunityButton.tsx
  src/components/common/Layout/Navigation/NavigationLinkButton.tsx
  src/components/common/Layout/Navigation/index.tsx
  src/components/common/Layout/index.tsx
  src/hooks/useDrawer.ts
  src/hooks/useWindowHeight.ts
  src/stores/drawer.ts
Labels: Priority: High, Feature

#29 로그인 모달 UI
  public/assets/delete-btn.svg
  src/components/common/Button/index.tsx
  src/components/common/Layout/Header.tsx
  src/components/login/BottonDrawer.tsx
  src/components/login/GoogleButton.tsx
  src/components/login/KakaoButton.tsx
  src/components/login/LoginButton.tsx
  src/stores/auth.ts
Labels: Feature

#31 Remote image error resolve 중
  next.config.js
  src/hooks/kakaoMap/useRecommendRandomRestaurant.ts
  src/types/kakaoMap.ts
Labels: Priority: Critical, Fix

#32 Remote image error 해결 중
  next.config.js
Labels: Priority: Critical, Fix

#33 Remote image error 해결 중
  next.config.js
Labels: Priority: Critical, Fix
